import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./components/navbar";
import Formulario from "./components/formulario";

export default function CadastrarReceita() {
  return (
    <>
      <Head>
        <title>Receitas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="position-absolute vw-100">
        <Navbar />
      </header>
      <main>
        <div className="container d-flex justify-content-center align-items-center vh-100">
          <div className="col-md-6">
            <Formulario />
          </div>
        </div>
      </main>
    </>
  );
}
