import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "@/styles/VisualizarReceita.module.css";
import Navbar from "./components/navbar";
import Head from "next/head";
import { Receita } from "@/interfaces/interfaces";
import Image from "next/image";

const VisualizarReceita = () => {
  const router = useRouter();
  const [receita, setReceita] = useState<Receita | null>(null);

  useEffect(() => {
    if (router.query) {
      const { id, titulo, descricao, receita, modoPreparo } = router.query;
      setReceita({ id, titulo, descricao, receita, modoPreparo } as Receita);
    }
  }, [router.query]);

  if (!receita) {
    return <div>Carregando...</div>;
  }

  async function excluirReceita() {
    try {
      const res = await fetch("/api/excluir-receita", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: receita?.id }),
      });

      if (res.ok) {
        alert("Receita excluída com sucesso!");
        router.push("/");
      } else {
        alert("Erro ao excluir a receita");
      }
    } catch (error) {
      console.error("Erro ao excluir a receita", error);
      alert("Erro ao excluir a receita");
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        <div className="container mt-5">
          <div className="card">
            <div className="row g-0">
              <div className="col-md-4">
                <img
                  className={`${styles.cardImg} img-fluid rounded-start`}
                  src="/comida.png"
                  alt="Imagem de capa da receita"
                />
              </div>
              <div className="col-md-8">
                <div className="card-body">
                  <h2 className="card-title">{receita.titulo}</h2>
                  <p className="card-text">
                    <strong>Descrição:</strong> {receita.descricao}
                  </p>
                  <hr />
                  <h4>Receita</h4>

                  <p className="card-text">{receita.receita}</p>
                  <hr />
                  <h4>Modo de preparo</h4>
                  <p className="card-text">{receita.modoPreparo}</p>
                  <button className="btn btn-danger" onClick={excluirReceita}>
                    Apagar
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default VisualizarReceita;
